version: "3.1"

services:
  notifierlite:
    build: 
      context: ./
    expose:
      - 4040
    ports:
      - "4040:4040"
    restart: always
    volumes:
      - config.ini:/config.ini
volumes:
  config.ini:
